# Generated by Django 2.2.7 on 2019-12-03 13:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type_id', models.CharField(max_length=255)),
                ('company_id', models.CharField(max_length=255)),
                ('file_creation_date', models.DateField()),
                ('file_upload_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_creation_time', models.TimeField()),
                ('file_gen_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=255)),
                ('measurement_date', models.DateField()),
                ('measurement_time', models.TimeField()),
                ('consumption', models.DecimalField(decimal_places=9, max_digits=9)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Record')),
            ],
        ),
    ]
